services:
  grugthink:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: grugthink
    ports:
      - "8080:8080"  # Web dashboard
    volumes:
      - ./data:/data:rw
      - ./grugthink_config.yaml:/app/grugthink_config.yaml:rw
    environment:
      - LOG_LEVEL=INFO
      - GRUGBOT_DATA_DIR=/data
    restart: unless-stopped