services:
  grugthink:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: grugthink
    ports:
      - "8080:8080"  # Web dashboard
    volumes:
      - ./data:/data:rw
      - ./grugthink_config.yaml:/app/grugthink_config.yaml:rw
      - ./personalities:/app/personalities:rw
    environment:
      - LOG_LEVEL=INFO
      - GRUGBOT_DATA_DIR=/data
    user: "1000:1000"  # Run as user ID 1000 to match host permissions
    restart: unless-stopped