version: '3.8'

# Development docker-compose with different image size variants
# Usage:
#   docker-compose -f docker-compose.dev.yml --profile lite up      # Lightweight
#   docker-compose -f docker-compose.dev.yml --profile optimized up # Optimized  
#   docker-compose -f docker-compose.dev.yml --profile original up  # Original

services:
  # Lightweight version - smallest image size (~200-300MB)
  grugthink-lite:
    build:
      context: .
      dockerfile: Dockerfile.lite
    container_name: grugthink-lite
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TRUSTED_USER_IDS=${TRUSTED_USER_IDS}
      - LOAD_EMBEDDER=False  # Disable ML features for smaller size
      - LOG_LEVEL=INFO
      - GRUGBOT_DATA_DIR=/data
    volumes:
      - ./grug-data:/data
    restart: unless-stopped
    profiles: ["lite"]

  # Optimized version - with ML but size-optimized (~1-2GB)
  grugthink-optimized:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: grugthink-optimized
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TRUSTED_USER_IDS=${TRUSTED_USER_IDS}
      - LOAD_EMBEDDER=True   # Enable ML features
      - LOG_LEVEL=INFO
      - GRUGBOT_DATA_DIR=/data
    volumes:
      - ./grug-data:/data
    restart: unless-stopped
    profiles: ["optimized"]

  # Original version (~3.5GB)
  grugthink-original:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grugthink-original
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TRUSTED_USER_IDS=${TRUSTED_USER_IDS}
      - LOAD_EMBEDDER=True
      - LOG_LEVEL=INFO
      - GRUGBOT_DATA_DIR=/data
    volumes:
      - ./grug-data:/data
    restart: unless-stopped
    profiles: ["original"]