version: "3.0"
description: "GrugThink Multi-Bot Configuration Example"

global_settings:
  log_level: "INFO"
  data_directory: "./data"
  enable_monitoring: true
  api_rate_limit: 100

environment:
  GRUGBOT_VARIANT: "prod"
  LOG_LEVEL: "INFO"
  LOAD_EMBEDDER: "True"

api_keys:
  gemini:
    primary: ""
    secondary: ""
    fallback: ""
  google_search:
    api_key: ""
    cse_id: ""
  discord:
    tokens:
      - id: "1"
        name: "Main Bot Token"
        token: ""
        active: true
        added_at: 1703876400

bot_templates:
  pure_grug:
    name: "Pure Grug"
    description: "Caveman personality only, no evolution"
    force_personality: "grug"
    load_embedder: true
    default_gemini_key: true
    default_google_search: false
    default_ollama: false
    custom_env: {}
    
  pure_big_rob:
    name: "Pure Big Rob"
    description: "norf FC lad personality only, no evolution"
    force_personality: "big_rob"
    load_embedder: true
    default_gemini_key: true
    default_google_search: false
    default_ollama: false
    custom_env: {}
    
  evolution_bot:
    name: "Evolution Bot"
    description: "Adaptive personality that evolves per server"
    force_personality: null
    load_embedder: true
    default_gemini_key: true
    default_google_search: false
    default_ollama: false
    custom_env: {}
    
  lightweight_grug:
    name: "Lightweight Grug"
    description: "Grug personality without semantic search"
    force_personality: "grug"
    load_embedder: false
    default_gemini_key: true
    default_google_search: false
    default_ollama: false
    custom_env: {}
    
  ollama_bot:
    name: "Ollama Bot"
    description: "Uses local Ollama instead of Gemini"
    force_personality: null
    load_embedder: true
    default_gemini_key: false
    default_google_search: false
    default_ollama: true
    custom_env:
      OLLAMA_URLS: "http://localhost:11434"
      OLLAMA_MODELS: "llama3.2:3b"