# Example: Single Bot Deployment
version: '3.8'

services:
  grugthink-single:
    build:
      context: ../../
      dockerfile: docker/single-bot/Dockerfile
    container_name: grugthink-single
    env_file:
      - ../../.env
    volumes:
      - ../../data:/data:rw
    environment:
      - GRUGBOT_DATA_DIR=/data
      - PYTHONPATH=/app/src
    restart: unless-stopped