name: Secret Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Grug needs all memories to find secrets
          lfs: true
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --regex